# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communicationProcess.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ommunicationProcess.proto\x12\x05proto\"4\n\x13\x63onfirmationMessage\x12\x1d\n\x15messageOfConfirmation\x18\x01 \x01(\t\"\x17\n\x07Replica\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\x91\x01\n\x12ReplicationService\x12=\n\x0fSendReplication\x12\x0e.proto.Replica\x1a\x1a.proto.confirmationMessage\x12<\n\x0egetReplication\x12\x1a.proto.confirmationMessage\x1a\x0e.proto.Replicab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'communicationProcess_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONFIRMATIONMESSAGE._serialized_start=37
  _CONFIRMATIONMESSAGE._serialized_end=89
  _REPLICA._serialized_start=91
  _REPLICA._serialized_end=114
  _REPLICATIONSERVICE._serialized_start=117
  _REPLICATIONSERVICE._serialized_end=262
# @@protoc_insertion_point(module_scope)
