# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import comunicationProcess_pb2 as comunicationProcess__pb2


class ReplicationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendReplication = channel.unary_unary(
                '/ReplicationService/SendReplication',
                request_serializer=comunicationProcess__pb2.Replica.SerializeToString,
                response_deserializer=comunicationProcess__pb2.confirmationMessage.FromString,
                )


class ReplicationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendReplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendReplication': grpc.unary_unary_rpc_method_handler(
                    servicer.SendReplication,
                    request_deserializer=comunicationProcess__pb2.Replica.FromString,
                    response_serializer=comunicationProcess__pb2.confirmationMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ReplicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReplicationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendReplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ReplicationService/SendReplication',
            comunicationProcess__pb2.Replica.SerializeToString,
            comunicationProcess__pb2.confirmationMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
