# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comunicationProcess.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63omunicationProcess.proto\x1a\x19google/protobuf/any.proto\"4\n\x13\x63onfirmationMessage\x12\x1d\n\x15messageOfConfirmation\x18\x01 \x01(\t\"-\n\x07Replica\x12\"\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any2G\n\x12ReplicationService\x12\x31\n\x0fSendReplication\x12\x08.Replica\x1a\x14.confirmationMessageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comunicationProcess_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONFIRMATIONMESSAGE._serialized_start=56
  _CONFIRMATIONMESSAGE._serialized_end=108
  _REPLICA._serialized_start=110
  _REPLICA._serialized_end=155
  _REPLICATIONSERVICE._serialized_start=157
  _REPLICATIONSERVICE._serialized_end=228
# @@protoc_insertion_point(module_scope)
